package MovieLovers20.Tutorial;

import MovieLovers20.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;


@Controller // This means that this class is a Controller
//@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class HelloCotroller {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

//    @PostMapping("/add") // Map ONLY POST Requests
//    public @ResponseBody String addNewUser (@RequestParam String name
//            , @RequestParam String email) {
//        // @ResponseBody means the returned String is the response, not a view name
//        // @RequestParam means it is a parameter from the GET or POST request
//
//        User n = new User();
//        n.setFirstName(name);
//        n.setLastName(name);
//        n.setEmail(email);
//        userRepository.save(n);
//        return "Saved";
//    }

//    @GetMapping("/all")
//    public @ResponseBody Iterable<User> getAllUsers() {
//        // This returns a JSON or XML with the users
//        return userRepository.findAll();
//    }
//
//    @GetMapping("/signup")//y
//    public String signupForm( Model model){//use a Model object to expose a new Greeting to the view template.
//        model.addAttribute("user", new User());
//        return "signup";
//    }
//    @PostMapping("/signup")//y
//    public String submitForm(@ModelAttribute("user") User user){
//        System.out.println(user);
//        userRepository.save(user);
//        if(user.getPassword() == ""){
//            return "registration-problem";
//        }
//        else{
//            return "result";
//        }
//    }

}
